### ISSUE TITLE
vspec.py can not include when there is no newline

### ISSUE THREAD

**Issue by SebastianSchildt** [COVESA/vehicle_signal_specification#145]
`#include` as the last line in a yaml does not work, becasue the parser expects a newline. As there is no error message this is somewhat annoying.

I think it is quite trivial to fix (see yamilify_includes in vspec.py) but unfortunately for policy reasons I am not allowed to make a PR here, so hoping someone can give it a quick look :D

**Comment by danielwilms** [comment]
@SebastianSchildt: good point. There was a discussion now about some further changes in VSS2, the include being one of it. will link the issues.

**Comment by gunnarx** [comment]
Hereby they are linked: #149 
As noted again today, it is probably obsolete once 149 is completed and implemented.
