### ISSUE TITLE
Describe Layering concept

### ISSUE THREAD

**Issue by danielwilms** [COVESA/vehicle_signal_specification#146]
Adding additions to the specification in terms of metadata and private nodes is crucial in succeeding with adoption of the specification. A lot of it is supported already by the tools. Now it's a question of giving best practices. 

Goal is a set of best practices, on how the specification can be deployed by introducing layers.

---
To get more information about the concept, please follow the discussion about layering in the [wiki](..vehicle_signal_specification/wiki//VSS-Layers-Concept)

**Comment by erikbosch** [comment]
I consider this one to be completed by the documentation in https://covesa.github.io/vehicle_signal_specification/rule_set/overlay/
