### ISSUE TITLE
Field Naming convention

### ISSUE THREAD

**Issue by geojins** [COVESA/vehicle_signal_specification#239]
Hi,
I noticed that few fields in the spec violates the naming convention from other.  For example.

Vehicle.IgnitionOn --> Field Starts with Upper case.  - This is the majority
Vehicle.accelerationTime --> Field starts with lower case. ( very few fields are like this)

Wondering if this is intended or an issue ?. 

Thanks,
Jins

**Comment by erikbosch** [comment]
@gunnarx - do we have a style guideline somewhere? If not, would it be an idea to somewhere in a repo create one, to e.g. state that "CamelCase" shall be the preferred pattern. If we have an agreement on style, we can then decide if we want to change existing items or leave them as is. If we decide to change all then we need to align on how to do it - it can be a bit cumbersome if we want to add a new item "AccelerationTime" but keep "accelertionTime" as deprecated for some time.

**Comment by danielwilms** [comment]
would be good to add to documentation. @danielwilms make proposal
