### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by gunnarx** [COVESA/vehicle_signal_specification#280]
Placeholder for discussion on allowable characters in the YAML definitions.

- Today: Which are the allowable characters, for example in signal names (right now only letters, numbers and "." encoded in ASCII seems assumed)?
- Future: What are future rules taking into account non-english languages, as well as the general consensus in many programming environments to use unicode file formats (UTF8 would be a good small step of course).
- Also, make sure to compare to YAML specs so that the result is still YAML compliant.

**Comment by crea7or** [comment]
Since JSON and YAML are UTF-8 by default there are not so many choices.

**Comment by oliveirarleo** [comment]
Well, I think more support is good, but this may interfere with some things already defined, for example `.` and `#` are already reserve.

Another thing is that someone will be able to use emojis and other characters that may not be desirable.
