### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by danielwilms** [COVESA/vehicle_signal_specification#292]

**Comment by slawr** [comment]
https://github.com/GENIVI/vehicle_signal_specification/blob/master/RELEASE_PROCESS.md mentions "create release note" as a release task but I can find no release note in the source or documentation. The nearest thing I could find was a v2.0 description in the "news" section of the live documentation, but then only for that release. Not for v2.1.

**Comment by erikbosch** [comment]
Release checklist and instructions extended, see https://github.com/COVESA/vehicle_signal_specification/wiki/Release-Instructions-and-Checklist. I think we can close this one and open newer ones if needed
