### ISSUE TITLE
Should there be any empty branches in VSS standard catalog?

### ISSUE THREAD

**Issue by gunnarx** [COVESA/vehicle_signal_specification#294]
While creating the GraphQL schema I found that several branches are defined but they have no leaves attached.

Examples:

- Vehicle.Media
- Vehicle.Powertrain.FuelCell
- Vehicle.OBD.O2Alt.Bank1.Sensor1
- Vehicle.OBD.O2Alt.Bank1.Sensor2
- Vehicle.OBD.O2Alt.Bank1.Sensor3
- Vehicle.OBD.O2Alt.Bank1.Sensor4
- Vehicle.OBD.O2Alt.Bank2.Sensor1
- Vehicle.OBD.O2Alt.Bank2.Sensor2
- Vehicle.OBD.O2Alt.Bank2.Sensor3
- Vehicle.OBD.O2Alt.Bank2.Sensor4

and the Private branch is also defined but empty unless something more is added to it.

Noteworthy is that some of the parents have only this empty branch, and are also otherwise empty.  
So if for example Sensor1 is removed, then suddenly Bank1 has no children.

**Question**: Should there be _any_ empty branches in the standard catalog or are they a mistake?
Is it worth defining some such branches (for future use or private use?)

**Comment by danielwilms** [comment]
remove media & fuelcell, check what OBD branches mean.

**Comment by gunnarx** [comment]
Discussion continues in #304.  Need a PR that removes media and fuelcell (until they are ready to be populated with actual info)
