### ISSUE TITLE
Units definitions both SI and common usage ?

### ISSUE THREAD

**Issue by petervolvowinz** [COVESA/vehicle_signal_specification#346]
So, I am looking at signal sets and their sometimes specified unit. I was wondering a bit about how we define units in VSS - http://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_unit_types/-  and  for example km/h and not mph. Both are commonly used and not SI-units , so we sometimes use SI and sometimes not. Is there a rule based decision to include non SI units ? Such as mph is commonly used as unit for this particular senor...or ? I am trying to build a table of units and their relations.

**Comment by oliveirarleo** [comment]
Discussions on vss-tools are running about having custom units (any unit you want to have basically). Currently, there is a [PR](https://github.com/GENIVI/vss-tools/pull/104) there, but there is the possibility of putting a file here with the units you want to support.

**Comment by erikbosch** [comment]
Discussed at meeting, no we do not have any strict policy as of today. we prefer SI units unless there is a good reason to use other units due to industry standard (e.g. km/h for speed, inch for rim size)

@petervolvowinz - are there any particular unit you ahve problems with or would like to remove/add?

**Comment by danielwilms** [comment]
@petervolvowinz: now there's as well a description in the [vss-tools FAQ](https://github.com/COVESA/vss-tools/blob/master/FAQ.md) with information on how to extend the list of units. Please have a look and check if there's something we can improve here, information you're missing or use cases, which aren't covered by now.
