### ISSUE TITLE
Look over old URLs, Google-hits etc.

### ISSUE THREAD

**Issue by gunnarx** [COVESA/vehicle_signal_specification#357]
A google search for VSS gives the following top hit:
https://genivi.github.io/vehicle_signal_specification/

but the docs are now here:
https://covesa.github.io/vehicle_signal_specification/

Since the repo moved, this URL is now different, and apparently github.io URLs do not redirect, like the git and normal web URLs do!

One option is to set up a repo at GENIVI/vehicle_signal_specification again, which would create the github.io link and the content could be just a pointer to the new one.   In the long run it might be better to let Google reindex the pages (Links that are 404 would usually be removed) but I think doing this might be a good idea for the short term.

Also, lots of references inside the source files -- PR is coming

**Comment by slawr** [comment]
Gunnar has perhaps already seen this but one issue I saw from the above is that the link from the VSS image in the top left of the documentation site pages results in a 404.

**Comment by danielwilms** [comment]
@slawr, @gunnarx: fixed the links

About the gh-pages, there's no really nice solution I think. If we re-setup the genivi/vss repo again, then all other redirects are broken, which are nice to have I think.
