### ISSUE TITLE
Only one trunk/no "frunk"

### ISSUE THREAD

**Issue by SebastianSchildt** [COVESA/vehicle_signal_specification#391]
We only support "a" trunk. Today many electric cars have an addtional trunk in the front (some examples in the table her https://einfacheauto.de/blog/welche-e-autos-haben-einen-frunk#welche-e-autos-haben-einen-frunk)

Wie should model a "frunk" or somehow instantiate trunk

**Comment by danielwilms** [comment]
PR Merged. Can be closed
