### ISSUE TITLE
Define/Rework or Remove VehicleIdentification.MeetsEmissionStandard

### ISSUE THREAD

**Issue by SebastianSchildt** [COVESA/vehicle_signal_specification#394]
We have an attribute MeetsEmissionStandard, that is not clearly defined

Came up in #389 

Copying discussions from there

Like all signals here it comes from schema.org (https://schema.org/docs/auto.home.html) and they do not specify it any further (https://schema.org/meetsEmissionStandard), seems to be a free text field that could contain text, URLs or anything.

But in general it seems like not much is happening in this area, I do not know if there are anyone actively maintaining the auto-related signals in schema.org. There is a W3C group but it seems to be quite dead. If no one use or maintain it we can consider removing the signals.

http://www.automotive-ontology.org/
https://www.w3.org/community/gao/

Having an attribute describing emission standard might still make sense. I just fear it would be quite some work to collect all possible allowed values. P19 https://www.continental-automotive.com/getattachment/8f2dedad-b510-4672-a005-3156f77d1f85/EMISSIONBOOKLET_2019.pdf/ gives some hint towards just the more recent ones...

**Comment by danielwilms** [comment]
@tguild can give more insights on the group. AFAIR they're focusing on an ontology for autonomous driving right now and are currently starting the activity. At the beginning, I think signals were taken from schema.org, and this seems to be one of those.

As for the catalogue I think it's a really nice source. We just have to find somebody to summerize.

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.
