### ISSUE TITLE
Allow HasXXX in addition to IsXX for boolean

### ISSUE THREAD

**Issue by SebastianSchildt** [COVESA/vehicle_signal_specification#395]
For some boolean sensors it might make more sense to name them "HasXX" instead of "IsXX", if we agree

 - change documentation to reflect that
 - change tooling to reflect that

**Comment by erikbosch** [comment]
While discussing prefix for boolean signals, do we want to separate between singular and plural. For example, if a signal concerns status of multiple items, e.g. both front wipers, shall we then use:

- IsWiperWorn (not really correct as it concerns multiple wipers)
- IsWipersWorn (not really grammatically correct)
- AreWipersWorn (grammatically correct, but not that usual to use "Are" as prefix, right?)

**Comment by danielwilms** [comment]
* `Is` instead of `Are`
* Find example for `has` and see it it's necessary

**Comment by erikbosch** [comment]
Meeting notes:

- No need for "has" right now, might be added later if we have a good example
- Decision: close this ticket
