### ISSUE TITLE
How to use tools to write vehicle end signals in VSS protocol

### ISSUE THREAD

**Issue by ScottProg** [COVESA/vehicle_signal_specification#410]
Because the amount of signal data at the vehicle end is very large, I want to know whether there is an official editor, such as vector, a tool for editing DBC files. Or a new project from 0 to 1, how to edit those signals?

**Comment by gunnarx** [comment]
It's a little unclear what you are asking about.

If you are asking for a tool to edit VSS catalogs, then the normal way is to simply edit the YAML files in any text editor.  You could choose a programming editor that gives some support for editing YAML.  There could be general YAML editors also on the web that might help - search for those.

If you are actually asking about editing DBC files, which define CAN data, then maybe https://github.com/GENIVI/CANdevStudio can help ?  (It might be moved to COVESA account later)

If you are asking about creating a _mapping_ between VSS and CAN signals then that is a typical question to be discussed within CVII Tech Stack - here is a page with more info: https://wiki.covesa.global/x/TAK5
