### ISSUE TITLE
Create recommendations on commenting

### ISSUE THREAD

**Issue by danielwilms** [COVESA/vehicle_signal_specification#411]
See discussion on #405

**Comment by danielwilms** [comment]
This ticket should reflect especially, but not only the question on how multiline comments are formatted.
Two ways:

**Starting with `|`**  
```
comment: |
        Indicates the 
        primary charging type fitted to the vehicle.
```
This format keeps newlines.

**Plain multiline**  
```
comment:     IEC_TYPE_1_AC refers to Type 1 as defined in IEC 62196-2. Also known as Yazaki or J1772 connector.
               IEC_TYPE_2_AC refers to Type 2 as defined in IEC 62196-2. 
```
This format doesn't keep newlines.

_More information_ 
The latter is "Yaml Plain style" see example 7.12 in https://yaml.org/spec/1.2.2/#733-plain-style. This is also described as "plain" in https://yaml-multiline.info/

Important to keep the csv output in mind.

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.
