### ISSUE TITLE
Support for high-order data types

### ISSUE THREAD

**Issue by paulboyes** [COVESA/vehicle_signal_specification#414]
Support for high-order data types, to correlate rich sensor data with metadata. Example for a camera sensor, we need to model the image URL with the object list as part of the same sensor. Or is there a different way they recommend modeling this data.
struct Camera {
   String uri;
   List<String> objectList;
}
Vehicle.ADAS.Camera:
   type: sensor
   datatype: Camera
   description: “...”

**Comment by erikbosch** [comment]
Structs as datatype is being discussed now and then, see e.g. #326

**Comment by danielwilms** [comment]
I think the discussion went less in the direction of complex data types but rather into one realization problem. I would close this one as duplicate to #326.

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.
