### ISSUE TITLE
Create an FAQ

### ISSUE THREAD

**Issue by paulboyes** [COVESA/vehicle_signal_specification#416]
There is a need to create an FAQ.  This should likely be added to the VSS documentation (aka github pages).  

In the meantime, a page has been added [here](https://wiki.covesa.global/display/WIK4/VSS+FAQ+-+Draft+Questions+and+Answers) to collect the questions and answers.  (A wiki account is needed to edit.)

**Comment by danielwilms** [comment]
It's fine for me, but can we do it in the wiki of this repo, so that we don't have the documentation all over the place?

**Comment by danielwilms** [comment]
summary: let's move FAQ into gh wiki and then decide where it ends up

**Comment by nijicompany** [comment]
hey there!
I am a newbie here and I have used Eclipse a lot and still using it, after a long thought I finally decided to start contributing to open source and Eclipse will be my first. So guys please suggest to me how can I get started in contributing. Any help and resource will be much valuable to me.
Thanks in advance

**Comment by erikbosch** [comment]
Hi @nijicompany - Contribution to VSS is welcome (but note that VSS is managed by the COVESA organization, not Eclipse, even if there are some Eclipse projects that use VSS, like https://github.com/eclipse/kuksa.val).

If you are interested in contributing to VSS I would suggest you to study existing signals and [tools](https://github.com/COVESA/vss-tools). Then, if you see improvement areas bring it up for discussion in and issue, or join the [weekly meetings](https://github.com/COVESA/vss-tools) at Tuesdays 16.00 CET to discuss it. You can also study existing issues to see if there is something you like to help out with. Actual contribution is by pull requests - but it could be good to discuss the idea first in an issue before starting implementation.



VSS depends on voluntary contributions. Provide improvements and extensions in Pull Requests to [VSS](https://github.com/COVESA/vehicle_signal_specification) and [VSS Tools](https://github.com/COVESA/vss-tools). Propose improvements in issues filed in GitHub. Participate in the [weekly meetings](https://github.com/COVESA/vehicle_signal_specification/wiki/Weekly-meeting).

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.
