### ISSUE TITLE
Signals on "Vehicle level", good or bad?

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#443]
I got a comment from someone working on visualizing VSS signals that it would be beneficial to not have (so many) individual signals on top-level, like `Vehicle.Speed` and `Vehicle.RoofLoad`, that it would be cleaner if top level only contained branches.

This would of course be possible to fix - it would be possible to move signals on vehicle level downwards into branches, maybe like having a branch `Specification` for typical attributes concerning e.g. length/height/weight (e.g.  `Vehicle.Specification.MaxRoofLoad`), and possibly another branch for status signals like speed and position. On the other hand, short names like `Vehicle.Speed" like today are quite attractive.

Any thoughts on existence of signals on "Vehicle"-level?

**Comment by erikbosch** [comment]
Meeting notes:
Sebastian: Don't like to move, short names good for programmers.
Ulf: Think it is fine to have signals on top level, but also does not give info on where e.g. vehicle.speed comes from. Visual argument no strength.

**Comment by danielwilms** [comment]
I would argue as well, that short names would beat almost everything else and most of them are directly related to the vehicle as such. Adding additional branch like `specification` would not help, only if you want to group and get something like `specification.*`. But I don't know how big of a use-case that is.

For the exact source, where it's measured, I think additional "private" meta-data would help (see `source` and `channel` in the graphQL schema.
