### ISSUE TITLE
VSS Logo

### ISSUE THREAD

**Issue by danielwilms** [COVESA/vehicle_signal_specification#451]
Yesterday in the call we discussed the suggestions for our new logo. If you want to have figma access and actively have an opinion and want to be part of the fine tuning, ping Sergej Stankeev on slack. For more general discussion, which one you like more in etc., post here.

![vss-logo-drafts](https://user-images.githubusercontent.com/2179688/171407148-706541df-b83d-4b23-bc5c-644b335f2f2a.png)

**Comment by danielwilms** [comment]
![vss_logo_update](https://user-images.githubusercontent.com/2179688/173229174-ec2d19b5-94ff-4d0e-99cc-735c560fef01.png)

In the last meeting we decided on going with the first row. Now discussions are about color and graph representation.

**Comment by alexjoybc** [comment]
@danielwilms is the slack channel public ?

**Comment by danielwilms** [comment]
> @danielwilms is the slack channel public ?

@alexjoybc feel free to join:
https://join.slack.com/t/w3cauto/shared_invite/zt-19rqpqs07-GX1Ib~K5BvL8F89fYiakcg

**Comment by SebastianSchildt** [comment]
Added some suggestions (removed already excluded ideas) here https://www.figma.com/file/iNjOi9R0sxKylVMlvKVaif/VSS-Logo-Playground?node-id=0%3A1. (lost write access to the original figma)

**Comment by SebastianSchildt** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3707124/174674818-f2b81ae8-b587-41a7-aef7-16251828b607.png">
 First was thinking the "complex tree" is too noisy, but after looking at it, I kind of like it

**Comment by danielwilms** [comment]
Thanks for the input. Personally, I like the original color scheme and logo best. But at the end it's a matter of taste.

@SebastianSchildt I don't find the logos in figma. Are there somewhere else, besides here?

**Comment by danielwilms** [comment]
meeting decision to go for 1)

voting:
1) 3
2) 2
3) 2

@danielwilms adds picture on what we voted on

**Comment by erikbosch** [comment]
First version integrated to documentation, see https://covesa.github.io/vehicle_signal_specification/
