### ISSUE TITLE
Typo in Battery.vspec (StateofHealth -> StateOfHealth)

### ISSUE THREAD

**Issue by ppb2020** [COVESA/vehicle_signal_specification#452]
StateofHealth should be StateOfHealth.

https://github.com/COVESA/vehicle_signal_specification/blob/a4971b1888f9834702b9a1860ae968b2752eeacb/spec/Powertrain/Battery.vspec#L76

**Comment by danielwilms** [comment]
Thanks for the pointer. I fixed it.
