### ISSUE TITLE
UUID in release artifacts

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#479]
As of default vss-tools by default include UUIDs, and thus release artifacts by default include UUIDs. 

Two thoughts:

- Is anyone actually using the UUIDs?
- Would it be an idea to change default so that UUID only is included if requested, implying that releases will be without UUID

**Comment by adobekan** [comment]
Would work for us to have optional build tag for UUID.

**Comment by erikbosch** [comment]
See meeting notes in https://github.com/COVESA/vss-tools/pull/189:

At least for minor releases (in 3.X) we should not remove UUID, but rather possibly generate both, and remove the old variant with UUID first in next major release (v4.0)

**Comment by erikbosch** [comment]
@adobekan - Found this issue, if you intend to refactor the UUID so it actually is useful then it might be an idea to keep UUID in released artifacts.

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.
