### ISSUE TITLE
driver.vspec feels a little under specified

### ISSUE THREAD

**Issue by slawr** [COVESA/vehicle_signal_specification#482]
### Micro view
https://github.com/COVESA/vehicle_signal_specification/blob/master/spec/Driver/Driver.vspec contains various leaves that read as being related to Driver Monitoring Systems (DMS). For example fatigue or alertness states.

However the vspec does not contain sufficient information in comments or the description to be able to interpret the values.

For example:

```
AttentiveProbability:
  datatype: float
  type: sensor
  unit: percent
  min: 0
  max: 100
  description: Probability of attentiveness of the driver.
```

At a minimum there is no explanation of what the extremes of the values represent. Does 0 represent fully attentive or asleep for example?

This is the case for all of the leaves using percents, i.e. FatigueLevel, AttentiveProbability and DistractionLevel.

Not knowing the background to the additions I can not easily add the missing text hence the issue raised here.

### Macro view
A related higher level question is whether two years on whether the fundamentals of the leaves still fit production needs? In Weds call Erik wondered if this had been somewhat of a placeholder originally.
As an example visual parts of Driver Monitoring Systems often monitor eye open state and point of focus (e.g. phone, windscreen, dashboard). Mapping that to these leaves may be difficult.

This would ideally get input from DMS vendors.

Personally I would suggest splitting this in two steps. The specification as released can be easily improved by addressing the lack of comments for the existing leaves and I would suggest that be the scope of this issue. More substantive change of the leaves themselves can be treated as a separate step.

**Comment by slawr** [comment]
Discussed in the VSS call today. I will send a PR fixing the description gap for the existing nodes.

**Comment by adobekan** [comment]
Note: focus would be on improving description of the existing VSS nodes. Thanks @slawr.
