### ISSUE TITLE
Logo Formats

### ISSUE THREAD

**Issue by paulboyes** [COVESA/vehicle_signal_specification#484]
We should provide other formats beside svg and/or build them with releases?  I made some today for COVESA Marketing at their request.  

![colored-with-white-text](https://user-images.githubusercontent.com/1558311/186541417-8f49569e-8b6a-4f45-95ac-ebe4933dd09d.png)
![colored-with-black-text](https://user-images.githubusercontent.com/1558311/186541421-d3199e3e-6452-4142-95b8-218d6f7d8a8c.png)
![black-with-black-text](https://user-images.githubusercontent.com/1558311/186541424-d1e4c439-612a-4381-9a80-2008563159e5.png)
![white-with-white-text](https://user-images.githubusercontent.com/1558311/186541425-bc3389f6-a1e6-4e1c-9f50-98b9199043af.png)

**Comment by SebastianSchildt** [comment]
I feel for the repo, we should only have "the source" (e.g. SVG) , that allows easy generation of everthing else , _unless_ we want to put more variants into the documentation here: I assume, you are thinking about something like a "marketing" page which provides logos in pdf, (e)ps, different PNG solutions etc.? That could either live  in our VSS documentation or in COVESA Wiki (somewhere around the "landing" page)

**Comment by erikbosch** [comment]
Meeting notes: For now only keep sources in git, building/generating artifacts shall be done manually, i.e. not included in git/github Makefile/CI/Release-process
