### ISSUE TITLE
Status and Handling of overlays/profiles

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#490]
As of know the status of the overlays in VSS is unclear. We need to clarify how to communicate whether overlays are considered to be part of official VSS, and/or how extensions of them shall be handled concerning e.g. testing. Also needs to be aligned with #473. This should better be discussed before merging #487.

Target:  Give comments until next meeting 2022-09-20.

**Comment by adobekan** [comment]
Notes 04.10.22
- Introduce guidelines and governance on how to handle overlays.
- Define ownership of the overlays and structure e.g. contrib and deprecation.

**Comment by erikbosch** [comment]
Closed now when #491 is merged
