### ISSUE TITLE
COVESA Contribution guidelines

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#493]
Took a look at the [COVESA Contribution guidelines](https://www.covesa.global/contribute) and found some topics that we have not been following strictly:

*Every contribution must carry the following sign-off line with your real name and email address:
"Signed-off-by: Firstname Lastname <[firstname.lastname@example.com](mailto:firstname.lastname@example.com)>"*

*When you submit code for the first time, the project maintainer will contact you and make sure that you are familiar with the DCO and answer all the questions you might have regarding contributions.*

I think it could be good to briefly discuss this - if we should start enforcing it. And how to manage if someone does not have an e-mail address of the format `firstname.lastname@mycompany.com`.

And if we are to follow it - would it be a possibility to enable a checker (like [DCO](https://probot.github.io/apps/dco/)) for all COVESA repos?

**Comment by erikbosch** [comment]
Meeting notes:

- COVESA Guidelines are up to date and shall be followed
- Paul with check within COVESA if repos can be setup to enforce the check
- Regardless, we should as part of reviews verify that there is a signoff before merging

**Comment by adobekan** [comment]
Note 04.09.22
@paulboyes will check if we can enable this check by default.

**Comment by erikbosch** [comment]
Now described in #491. But we shall maybe leave it open until we have a conclusion on the automatic check
