### ISSUE TITLE
Use only singular names for branches

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#541]
I see inconsistencies regarding the naming of branches. Most of the branches that can be instantiated are correctly named with the singular form (e.g., Door, Wheel, Window, etc.) 

However, there are cases that use the plural form (e.g., Lights)

I recommend to enforce the use of singular names.

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.
