### ISSUE TITLE
Move documentation to other repository

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#543]
As of today this repository defines both catalog syntax and also the actual catalog. As we move in the direction of decoupling metamodel/syntax and catalog most documentation should better be moved to a separate repository. 

This issue is to agree on way foward. If we agree to move documentation to a separate repository we could possibly also extend the scope of the documentation to handle general "VehicleAPI" aspects

Possibly a new repo called "vehicle_api_documentation"?

**Comment by SebastianSchildt** [comment]
Some related issue: https://github.com/COVESA/vehicle_signal_specification/issues/268

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.
