### ISSUE TITLE
Add new signals for charging 

### ISSUE THREAD

**Issue by adobekan** [COVESA/vehicle_signal_specification#563]
As discussed in PR https://github.com/COVESA/vehicle_signal_specification/pull/536

> If we assume that we need to support two scenarios:

    The user/driver can specify a minimum limit. When charging has reached that limit the user will be informed in his app, but charging will continue
    The user/driver can specify a maximum limit (or it is decided by vehicle, possibly fixed at 100%). When charging has reached that limit the user will be informed in his app, and charging will stop.

Then we maybe need four signals (names can be discussed):

    Charging.ChargeLimit to be replaced with Charging.MinimumChargeLimit and Charging.MaximumChargeLimit
    Charging.TimeToComplete to be replaced by Charging.TimeToMinimumChargeLimit and Charging.TimeToMaximumChargeLimit

But which time that will actually will be shown in the vehicle or in the app may vary, I assume. If you just want enough charge to be able to drive home then I assume Charging.TimeToMinimumChargeLimit is what you are most interested in.

**Comment by ppb2020** [comment]
Bringing in my comment from PR#536:



Regarding:

> The user/driver can specify a minimum limit. When charging has reached that limit the user will be informed in his app, but charging will continue

Would it make sense for the app to inform the user based on its own monitoring of the charge level, as opposed to pushing the decision and monitoring into the vehicle? What if there are multiple applications each with their own minimum and maximum charge limits for the same vehicle (two partners sharing a vehicle)?

If a limit is set using Charging.MinimumChargeLimit, what is the signal that is triggered by reaching this limit? As well, from what direction is this limit monitored? Charging (as implied by the name) or discharging (where the user may want to be informed when the charge level reaches this limit while discharging)?
