### ISSUE TITLE
Future Releases: Release unit file as well

### ISSUE THREAD

**Issue by SebastianSchildt** [COVESA/vehicle_signal_specification#616]
I wonder, whether we should also release the units file, as it is now part of the model.

I just wanted to use the flattened yaml output as the base for some overlay, and while I could download the yaml form the 4.0 release, the tools complain about missing unit file. That one I now needed to get out of the source tree. Might be better to put it into a release as well.

(I think not a breaker for 4.0, but maybe for 4.1 we should consider it)

**Comment by erikbosch** [comment]
Included in latest release
