### ISSUE TITLE
Struct support - how to support it in standard catalog (if we want to use it)

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#617]
For structs we have the current status:

- Supported in the most common tools, but not others (so starting to use structs in standard catalog would make CI fail)
- We have agreed to use it restrictively in standard catalog.

But i think it would be good to start agreeing on how we would use it in standard catalog, if we would start to use it. One reason is that we today say that we only support a single type tree, so we need to coordinate name.

**Single Type Tree**

- Use `Types` as top name?
- Use `Types.Vehicle` as top branch for types defined by VSS-project? Possible type-names could then be `Types.Vehicle.Location` (simple location with lat/lon), `Types.Vehicle.GNSSLocation` (location with more fields, like altitude, time and accuracy), `Types.Vehicle.Powertrain.TractionBattery.CellStatus`
- This would allow other projects to use names like `Types.Infrastructure` and deployments to use private branches like `Types.Bosch`
- With this approach a natural storing point could be `spec/Types` in this repository.

**Multiple Type Trees**

Or do we want to extend syntax (and tooling) to support multiple type trees, so that we can use something like `VehicleTypes` as top domain, other projects/organization might use other names as top domain?

**Comment by petervolvowinz** [comment]
One principal discussion to have is whether we should concern our selfes with other domains or just focus on our domain. Is it beneficial for the adaption of VSS to define our model for other domains ?  I believe that providing a way for private branches like Types.branch is enough.

**Comment by erikbosch** [comment]
> One principal discussion to have is whether we should concern our selfes with other domains or just focus on our domain. Is it beneficial for the adaption of VSS to define our model for other domains ? I believe that providing a way for private branches like Types.branch is enough.

Then maybe stating that VSS-project will use `Types` as top name for types (if/when we are to use types in standard catalog) is sufficient for now.

**Comment by erikbosch** [comment]
Meeting discussion:

- Ulf: `Types.Vehicle` could be a good prefix
