### ISSUE TITLE
Hydrofoil signals

### ISSUE THREAD

**Issue by JonathanForce** [COVESA/vehicle_signal_specification#723]
Hello,

BRP is going to market an electric board with a foil called Sea-Doo Rise: Electric Hydrofoil.
https://sea-doo.brp.com/ca/en/sea-doo-rise.html

This board has a remote control that allows the user to get information about the board and control it to manage power and speed, for example.

If I want to add signals relating to this remote control, such as its battery level, what is the best option?

Should I create an overlay in the "profiles" directory as was done for motorbike.vspec? This could be an overlay called hydrofoil.vspec for example, as BRP is not the only manufacturer to market this type of product (liftfoils: https://liftfoils.com/ca, filteboard: https://fliteboard.com).

What do you think?
Is there another/better option?

**Comment by erikbosch** [comment]
I see some different alternatives:

- Consider boards/foils to be vehicles - if so it make perfect sense to have an overlay/profile for foil-specific data. But I do not know how many existing VSS signals that would be useful for the foil-case. If only a very limited number of signals will be reused treating it as a VSS standard catalog profile maybe does not make sense.
- Consider it to be "something else" That is what we did with representation for charging stations where we created a separate [tree](https://github.com/COVESA/ev_charging). That could give you a "cleaner" tree

In both cases I think we need to discuss if foils/boards are within the current scope of COVESA and/or the COVESA VSS-project. We are now and then discussing VSS-signals for commercial vehicles, motorbikes and agricultural machines, but representation for watercraft vehicles has so far not been prioritized. So we need to decide if we want to extend scope to watercraft, and if we do so we need to decide if the foil use case is so specific that it should be a separate foil profile/tree, or if it can be generalized as a watercraft profile/tree. Maybe you could use the same profile/tree to control a tug boat.
