### ISSUE TITLE
Documentation generation framework (Learn) is deprecated

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#751]
In VSS-project we currently use https://github.com/matcornic/hugo-theme-learn as theme for Hugo generation to create our [generated documentation](https://covesa.github.io/vehicle_signal_specification/)

That template is deprecated and it is recommended to switch to https://github.com/McShelby/hugo-theme-relearn, also promoted at https://themes.gohugo.io/themes/hugo-theme-relearn/. It is claimed to be easy to replace.

_This is in no way an urgent change, there are currently no known problems affecting us with the old deprecated theme._

**Comment by jdacoello** [comment]
I like the template and support the idea to move to the new maintained theme. It can be targeted for the next major release. We can take that chance to refresh the look of the pages and update the documentation, if needed.
