### ISSUE TITLE
Bug: Conflicting key in TractionBattery

### ISSUE THREAD

**Issue by doosuu** [COVESA/vehicle_signal_specification#774]
https://github.com/COVESA/vehicle_signal_specification/blob/c45a5bda1599f8b49fa542ae56e7023ced2ae0c1/spec/Powertrain/TractionBattery.vspec#L282

The YAML item linked above has both type: actuator and type: sensor. This is not allowed by YAML and should be fixed.

**Comment by erikbosch** [comment]
Thanks for reporting!
