### ISSUE TITLE
Uniform way of defining enums

### ISSUE THREAD

**Issue by danielwilms** [COVESA/vehicle_signal_specification#91]
Right now we have different notations for enums. Some examples:

**Underscore** ```Vehicle.Drivetrain.FuelSystem.HybridType```: unknown / not_applicable / stop_start / belt_ISG / CIMG / PHEV 

**Space**  ```Vehicle.Drivetrain.Transmission.DriveType```: unknown / forward wheel drive / rear wheel drive / all wheel drive

**Camel case** ```Vehicle.Cabin.RearShade.Switch```: Inactive / Close / Open / OneShotClose / OneShotOpen

I think it would make sense to agree on a notation, so that it's easier and more intuitive for the developer. I'd go for lower camel case, as we have many lower case enums already. Opinions?

**Comment by danielwilms** [comment]
related to #239

**Comment by erikbosch** [comment]
Related to #399

**Comment by erikbosch** [comment]
Considered fixed by the PRs mentioned above
